name: "My-action"
description: "test my action"

inputs:
  message: 
    description: "The message to print"
    required: true
    default: "Hola"


runs:
  using: "composite" #Permiten agrupar pasos comunes, por ejemplo los steps

  steps:
    - name: Hola Mundo
      #run: echo "Hola Mundo"
      run: echo "Hola ${{inputs.message}}"
      shell: bash