name: Test

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
            
      - name: ls
        run: |
          ls -la
          cd ./.github/workflows
          ls -la
          chmod +x script.sh
          ./script.sh

          

