name: Test Composite Actions

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    #vamos a definir un servicio, en este caso con mysql 
    #say-hello:
    #runs-on: ubuntu-latest
    # "
    # services: #directiva de servicio
    #   mysql: 
    #     image: mysql:5.7
    #     env:
    #       MYSQL_ROOT_PASSWORD: example
    #     ports:
    #       - 3306:3306
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379    
    # "
    #Definir variables de entorno. 
    env:
      MY_VAR: Mi varible de entorno        

    steps: #Un step no puede usr uses y run al mismo tiempo
      - name: Checkout
        uses: actions/checkout@v4.2.0
        
            
      - name: ls
        run: | #Operador pai
          ls -la
          cd ./.github/workflows
          ls -la
          chmod +x script.sh
          ./script.sh

          
      - name: reutilizar_actions
        uses: ./.github/workflows/actions/my-actions
        with:  #Se usa lara poder pasarle parametros a dichas actions
          message: "Harol"
    
      - name: Varibles_de_entorno_Jobs
        #run: echo "valor $MY_VAR"
        env:
          STEP_MY_VR: nivel step
        run: echo "valor $STEP_MY_VAR"
          

            
