name: Test

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
            
      - name: ls
        run: |
          
          ll
          chmod +x /home/runner/work/_temp/5e90abf7-4e46-4758-a6fa-e375017c6d6a.sh 
          

